apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/hevel86/BrainiacOps
    targetRevision: HEAD
    path: kubernetes/infrastructure/tailscale-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
