apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: openclaw-secrets
  namespace: default
  labels:
    app: openclaw
spec:
  secretName: openclaw-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "df8e6e74-fc87-414f-91e8-b386011bc6ae"
      secretKeyName: OPENAI_API_KEY
