# Reference only. This is intentionally not included by the Plex kustomization.
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: plex
  namespace: default
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.torquasmvo.com`)
      kind: Rule
      services:
        - name: plex
          namespace: default
          port: 32400
          scheme: https
          serversTransport: plex
  tls:
    secretName: traefik-dashboard-tls
