# kubernetes/apps/default/maintainerr/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 10Gi
