apiVersion: v1
kind: Service
metadata:
  name: brainiac-hostinger
  namespace: default
  annotations:
    tailscale.com/tailnet-fqdn: brainiac-hostinger.tailca892.ts.net
spec:
  type: ExternalName
  externalName: placeholder
