apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: immich-secrets
  namespace: default
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
spec:
  secretName: immich-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "af62c863-7337-4f13-b8ec-b4b20165ebbf"
      secretKeyName: DB_PASSWORD
