---
# kubernetes/infrastructure/media-pvc/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Ti
  volumeName: media-movies-pv-default
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  volumeName: media-tv-pv-default
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  volumeName: audiobookshelf-audiobooks-pv
  storageClassName: ""
  volumeMode: Filesystem
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: media-downloaders-pvc
#   namespace: default
# spec:
#   accessModes: ["ReadWriteMany"]
#   resources:
#     requests:
#       storage: 2Ti
#   volumeName: media-downloaders-pv-default
#   storageClassName: ""
#   volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-comics-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 30Gi
  volumeName: media-comics-pv-default
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  volumeName: sabnzbd-downloads-pv-default
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-vpn-data
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: transmission-vpn-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-roms-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 3Ti
  volumeName: fast-roms-pv-default
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: immich-library-pv
  storageClassName: ""
  volumeMode: Filesystem
