apiVersion: v1
kind: Service
metadata:
  name: azahar
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: azahar.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.222
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app.kubernetes.io/name: azahar
