apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: server
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  nfs:
    server: truenas1-nfs.torquasmvo.internal
    path: /mnt/fast/pictures/immich
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
