# kubernetes/infrastructure/monitoring/alertmanager-ntfy/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy-config
  namespace: monitoring
data:
  config.yml: |
    http:
      addr: :8000
    ntfy:
      baseurl: https://ntfy.botty-mcbotface.com
      notification:
        topic: prometheus
        templates:
          title: |
            {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
          description: |
            {{ index .Annotations "description" }}
