# kubernetes/infrastructure/monitoring/alertmanager-ntfy/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-ntfy
  namespace: monitoring
  labels:
    app: alertmanager-ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-ntfy
  template:
    metadata:
      labels:
        app: alertmanager-ntfy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: alertmanager-ntfy
        image: ghcr.io/vitorfhc/promntfy:latest
        env:
        - name: PROMNTFY_NTFY_URL
          value: "https://ntfy.botty-mcbotface.com"
        - name: PROMNTFY_NTFY_TOPIC
          value: "prometheus"
        - name: PROMNTFY_NTFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: ntfy-token
              key: token
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 10m
