# kubernetes/infrastructure/monitoring/alertmanager-ntfy/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-ntfy
  namespace: monitoring
  labels:
    app: alertmanager-ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-ntfy
  template:
    metadata:
      labels:
        app: alertmanager-ntfy
    spec:
      containers:
      - name: alertmanager-ntfy
        image: ghcr.io/alexbakker/alertmanager-ntfy:1.0.1
        env:
        - name: NTFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: ntfy-token
              key: token
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        volumeMounts:
        - name: config
          mountPath: /app/config.yml
          subPath: config.yml
          readOnly: true
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 10m
      volumes:
      - name: config
        configMap:
          name: alertmanager-ntfy-config
