apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/hevel86/BrainiacOps
    targetRevision: HEAD
    path: kubernetes/apps/default/n8n
  ignoreDifferences:
    - group: ""
      kind: Service
      name: printer-pi
      namespace: default
      jsonPointers:
        - /spec/externalName
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - CreateNamespace=true
