apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listenarr-config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 5Gi
