apiVersion: v1
kind: Service
metadata:
  name: listenarr
  namespace: default
  labels:
    app: listenarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: listenarr.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.244
  selector:
    app: listenarr
  ports:
    - name: http
      port: 4545
      targetPort: http
      protocol: TCP
