apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: default
  labels:
    app: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:8
          ports:
            - containerPort: 3000
          args:
            - gotenberg
            - --chromium-disable-javascript=false
            - --chromium-allow-list=.*
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
