{
 "title": "NUT UPS Dashboard (10914)",
 "description": "https://technicalramblings.com/blog/setting-grafana-influxdb-telegraf-ups-monitoring-unraid/",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kwhprice", "label": "kWh Price", "query": "0.12" },
   { "name": "currency", "label": "Currency", "query": "$,€,£,C$,kr,₽,¥" },
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "UPS Load %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "Load %"
    },
    {
     "expr": "(network_ups_tools_ups_load{ups=\"$ups\"} * on(ups) network_ups_tools_ups_realpower_nominal{ups=\"$ups\"}) / 100",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}",
     "legendFormat": "Charge"
    }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwh" } },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum_over_time((network_ups_tools_ups_load{ups=\"$ups\"} * on(ups) network_ups_tools_ups_realpower_nominal{ups=\"$ups\"} / 100)[24h:1m]) * 60 / 3600 / 1000",
     "legendFormat": "kWh"
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(network_ups_tools_ups_load{ups=\"$ups\"} * on(ups) network_ups_tools_ups_realpower_nominal{ups=\"$ups\"}) / 100",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time((network_ups_tools_ups_load{ups=\"$ups\"} * on(ups) network_ups_tools_ups_realpower_nominal{ups=\"$ups\"} / 100)[24h:1m])",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "alias": "Costs" }
   ]
  },
  {
   "title": "Load kWh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "alias": "Wh" }
   ]
  },
  {
   "title": "This Week's Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {}
   ]
  },
  {
   "title": "This Week Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    { "alias": "Costs" },
    { "alias": "kWh" }
   ]
  },
  {
   "title": "This Month Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    { "alias": "Costs" },
    { "alias": "kWh" }
   ]
  },
  {
   "title": "This Week's Cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {}
   ]
  },
  {
   "title": "This Month's Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    { "alias": "kWh" }
   ]
  },
  {
   "title": "This Month's Cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {}
   ]
  },
  {
   "title": "Last 7 Day Power Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    { "alias": "Costs" },
    { "alias": "kWh" }
   ]
  },
  {
   "title": "Last Month Power Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    { "alias": "Costs" },
    { "alias": "kWh" }
   ]
  },
  {
   "title": "This Year's Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    { "alias": "kWh" }
   ]
  },
  {
   "title": "This Year's Cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {}
   ]
  },
  {
   "title": "Estimated Yearly Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    { "alias": "Costs" }
   ]
  },
  {
   "title": "This Years Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    { "alias": "Costs" },
    { "alias": "kWh" }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "alias": "Costs" }
   ]
  },
  {
   "title": "UPS Load vs Time left",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "alias": "W" },
    { "alias": "T" }
   ]
  }
 ]
}