apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: paperless-secrets
  namespace: default
  labels:
    app: paperless-ngx
spec:
  secretName: paperless-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "c6d8b745-e711-47b3-88cf-b40e016ae838"
      secretKeyName: PAPERLESS_SECRET_KEY
    - bwSecretId: "e2000fde-1ab9-4abf-a361-b40e016b2031"
      secretKeyName: PAPERLESS_DBPASS
    - bwSecretId: "6add4516-8aa9-4dad-b477-b40e016b38aa"
      secretKeyName: PAPERLESS_ADMIN_USER
    - bwSecretId: "af31eec4-c9f5-4efe-b724-b40e016b531b"
      secretKeyName: PAPERLESS_ADMIN_PASSWORD
