apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutify-logs
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutify-instance
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutify-ssl
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutify-nut-config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 1Gi
