apiVersion: v1
kind: Service
metadata:
  name: nutify
  namespace: default
  labels:
    app: nutify
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nutify.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.206
  selector:
    app: nutify
  ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
