apiVersion: v1
kind: Service
metadata:
  name: watchstate
  namespace: default
  labels:
    app: watchstate
  annotations:
    external-dns.alpha.kubernetes.io/hostname: watchstate.torquasmvo.internal
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.243
  selector:
    app: watchstate
  ports:
    - name: http
      port: 8080
      targetPort: http
