# kubernetes/infrastructure/fast-pvc/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fast-pvc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/hevel86/BrainiacOps
    targetRevision: HEAD
    path: kubernetes/infrastructure/fast-pvc
    directory:
      exclude: "app.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
