apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: tracearr-secrets
  namespace: default
  labels:
    app: tracearr
spec:
  secretName: tracearr-secrets
  organizationId: "9f7b77c1-18f7-4dc8-b252-b274015d6c40"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "b8fbee64-e2da-4143-ba0c-b4240131ebf3"
      secretKeyName: TRACEARR_DB_PASSWORD
    - bwSecretId: "e95084ab-2cf9-4ab2-a816-b424013224d8"
      secretKeyName: TRACEARR_JWT_SECRET
    - bwSecretId: "e149ffad-99ca-49b9-aecf-b42401323736"
      secretKeyName: TRACEARR_COOKIE_SECRET
